In [1]:
#11.5
import numpy as np

a = np.arange(1,17).reshape(4,4)
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [5]:
#11.6

a = np.random.random(size = 10)
print('a = ', a)
print('최댓값 : ', np.max(a))
print('최솟값 : ', np.min(a))
print('평균값 : ', np.mean(a))

a =  [0.77782806 0.02852639 0.37562387 0.86916414 0.90993845 0.79199506
 0.82930557 0.06563475 0.03333911 0.52490955]
최댓값 :  0.9099384478232887
최솟값 :  0.028526386810335924
평균값 :  0.5206264937739713


In [25]:
#11.7

n = int(input('n을 입력하시오 : '))
ary = np.zeros((n,n), dtype = np.int32)
ary[::2, ::2] = 1
ary[1::2, 1::2] = 1
print(ary)

n을 입력하시오 : 5
[[1 0 1 0 1]
 [0 1 0 1 0]
 [1 0 1 0 1]
 [0 1 0 1 0]
 [1 0 1 0 1]]


In [24]:
#11.8

n = int(input('n을 입력하시오 : '))
ary = np.zeros((n,n), dtype = 'int32')
for i in range(n):
    ary[i, i] = i+1
print(ary)

n을 입력하시오 : 6
[[1 0 0 0 0 0]
 [0 2 0 0 0 0]
 [0 0 3 0 0 0]
 [0 0 0 4 0 0]
 [0 0 0 0 5 0]
 [0 0 0 0 0 6]]


In [29]:
#11.9

n = int(input('n을 입력하시오 : '))
a = np.ones((n,n), dtype = 'int32')
print('a 행렬')
print(a)
b = a
b[1:-1, 1:-1] = 0
print('b 행렬')
print(b)

n을 입력하시오 : 5
a 행렬
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
b 행렬
[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [31]:
#11.10

n = int(input('n을 입력하시오 : '))
a = np.ones((n,n), dtype = np.int32)
print('a 행렬')
print(a)
c = a
c[0] = 0
c[-1] = 0
c[:, 0] = 0
c[:, -1] = 0
print('c 행렬')
print(c)

n을 입력하시오 : 5
a 행렬
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
c 행렬
[[0 0 0 0 0]
 [0 1 1 1 0]
 [0 1 1 1 0]
 [0 1 1 1 0]
 [0 0 0 0 0]]


In [47]:
#11.11

a = np.array([0,10,20,40,60,80])
b = np.array([0, 20])
bool_list = []
flag = False
for i in range(a.size):
    for j in range(b.size):
        if a[i] == b[j]:
            bool_list.append(True)
            flag = True
            break
        else:
            flag = False
            continue
    if flag == False:
        bool_list.append(False)
    
print('a 배열 : ', a)
print('b 배열 : ', b)
print(bool_list)

a 배열 :  [ 0 10 20 40 60 80]
b 배열 :  [ 0 20]
[True, False, True, False, False, False]


In [79]:
#11.12

x = np.array([[10,20,40,60], [10,20,40,40]])
num_list = []
rows, cols = x.shape
for i in range(rows):
    for j in range(cols):
        if x[i,j] in num_list:
            continue
        else:
            num_list.append(x[i,j])
num_list.sort()
for element in num_list:
    temp = sum(x==element)
    count = sum(temp)
    print('{} : {}번'.format(element, count))
print()
    
x = np.array([[80, 120,40], [60,80,120], [40,40,40]])
num_list = []
rows, cols = x.shape
for i in range(rows):
    for j in range(cols):
        if x[i,j] in num_list:
            continue
        else:
            num_list.append(x[i,j])
num_list.sort()
for element in num_list:
    temp = sum(x==element)
    count = sum(temp)
    print('{} : {}번'.format(element, count))

10 : 2번
20 : 2번
40 : 3번
60 : 1번

40 : 4번
60 : 1번
80 : 2번
120 : 2번


In [89]:
#11.14
n = int(input('n을 입력하시오 : '))
ary = np.eye(n)
for i in range(n):
    ary[-1-i, i] = 1
print(ary)

n을 입력하시오 : 6
[[1. 0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 1. 0.]
 [0. 0. 1. 1. 0. 0.]
 [0. 0. 1. 1. 0. 0.]
 [0. 1. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0. 1.]]


In [95]:
#11.15
n = int(input('n을 입력하시오 : '))
ary = np.zeros((n,n))
for i in range(n):
    ary[i, :i+1] = 1
print(ary)

count = np.sum(ary)
print('\n행렬의 모든 원소의 합:', count)

r_count = np.sum(ary, axis = 0)
print('\n행렬의 행 방향 성분의 합: ', r_count)

c_count = np.sum(ary, axis = 1)
print('\n행렬의 행 방향 성분의 합: ', c_count)

n을 입력하시오 : 5
[[1. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0.]
 [1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 0.]
 [1. 1. 1. 1. 1.]]

행렬의 모든 원소의 합: 15.0

행렬의 행 방향 성분의 합:  [5. 4. 3. 2. 1.]

행렬의 행 방향 성분의 합:  [1. 2. 3. 4. 5.]


In [100]:
#11.17
a = np.array([[0,0,0,0,0], [0,1,1,1,0], [0,1,2,1,0], [0,1,1,1,0], [0,0,0,0,0]])
b = a[1:4, 1:4]
print('배열 b')
print(b, '\n')
c= a[:3, :3]
print('배열 c')
print(c, '\n')
d = a[:3, 1:4]
print('배열 d')
print(d, '\n')
e = a[1:4, 2:]
print('배열 e')
print(e, '\n')
f = a[2]
print('배열 f')
print(f, '\n')

배열 b
[[1 1 1]
 [1 2 1]
 [1 1 1]] 

배열 c
[[0 0 0]
 [0 1 1]
 [0 1 2]] 

배열 d
[[0 0 0]
 [1 1 1]
 [1 2 1]] 

배열 e
[[1 1 0]
 [2 1 0]
 [1 1 0]] 

배열 f
[0 1 2 1 0] 

