In [10]:
#numpy의 ndarray 사용

import numpy as np
a = np.array([1,2,3]) #numpy의 array클래스를 사용하여 객체 생성
print('a :', a) 
print('a.shape : ', a.shape)  #a 객체의 형태
print('a.ndim : ', a.ndim)  #a 객체의 차원
print('a.dtype : ', a.dtype) #a 객체 내부 자료형
print('a.itemsize : ', a.itemsize)  #a 객체 내부 자료형이 차지하는 메모리 크기(byte) -> int의 byte수
print('a.size : ', a.size)  #a 객체의 전체 크기

a : [1 2 3]
a.shape :  (3,)
a.ndim :  1
a.dtype :  int32
a.itemsize :  4
a.size :  3


In [11]:
#numpy와 데이터형

a = np.array([1,2,3], dtype = 'int32')
b = np.array([4,5,6], dtype = 'int64')  #int32와 int64는 저장용량의 범위가 다름. 보통 int만 쓰면 int32를 의미
print(a.dtype)
print(b.dtype)
c = a+b
print(c.dtype)  #큰 공간에 맞춤

int32
int64
int64


In [12]:
#ndarray 배열을 생성할 때 주의점 : 반드시 대괄호를 사용하여 리스트 형식의 데이터를 인자로 넣어야 함

a = np.array(1,2,3,4)
#a = np.array([1,2,3,4]) 가 맞는 구문

TypeError: array() takes from 1 to 2 positional arguments but 4 were given

In [13]:
# ndarray 배열을 생성할 때 주의점 : 넘파이의 ndarray는 리스트와 달리 서로 다른 자료형의 값을 원소로 가질 수 없음

a = np.array([1, 'two', 3, 4], dtype = np.int32)  #데이터 타입 지정은 np.int32와 같이 np의 속성 값으로 지정해도 되고,
                                                  # 'int32' 와 같이 문자열 형식으로 지정해도 된다.

ValueError: invalid literal for int() with base 10: 'two'

In [15]:
# 자료형을 섞어서 쓴 뒤 뒤에 자료형을 명시하지 않을 경우 전부 str형으로 자동 형변환. -> 사칙연산 등의 연산 사용 불가

a = np.array([2, 'two', 3, 4])
print(a)

['2' 'two' '3' '4']


In [31]:
#LAB 11-1

#1
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print('array(',a,')')

#2
b = np.array(range(0,10))
print('array(',b,')')

#3
c = np.array(range(0,10,2))
print('array(',c,')')

#4
print('c.shape =', c.shape)
print('c.ndim =', c.ndim)
print('c.dtype =', c.dtype)
print('c.size =', c.size)
print('c.itemsize =', c.itemsize)

array( [0 1 2 3 4 5 6 7 8 9] )
array( [0 1 2 3 4 5 6 7 8 9] )
array( [0 2 4 6 8] )
c.shape = (5,)
c.ndim = 1
c.dtype = int32
c.size = 5
c.itemsize = 4


In [33]:
#ndarray의 메소드와 주요 함수

#ndarray
a = np.array([1,2,3])
print(a.max())
print(a.min())
print(a.mean())

#flatten
a = np.array([[1,1], [2,2], [3,3]])
print(a.flatten()) #평탄화 메소드

3
1
2.0
[1 1 2 2 3 3]


In [42]:
#LAB 11-2
#1
a = np.array([23, 45, 67, 7, 2, 30, 34, 82])
print(a)
print('최댓값 : ', a.max())
print('최솟값 : ', a.min())
print('평균 : ', a.mean())
print()

#2
b = np.array(np.random.randint(0,100))
print(b)
print('최댓값 : ', a.max())
print('최솟값 : ', a.min())
print('평균 : ', a.mean())
print()

#3
c = np.append(a,b)
print('c =', c)

[23 45 67  7  2 30 34 82]
최댓값 :  82
최솟값 :  2
평균 :  36.25

75
최댓값 :  82
최솟값 :  2
평균 :  36.25

c = [23 45 67  7  2 30 34 82 75]


In [43]:
#ndarray 덧셈(shape이 같은 경우)
a = np.array([1,2,3])
b = np.array([4,5,6])
c = a+b
print(c)

#ndarray 곱셈(shape이 다른 경우 - 오류)
#a = np.array([1,2])
#b = np.array([3,4,5])

[5 7 9]


In [48]:
#이차원 ndarray 연산
a = np.array([[1,2], [3,4]])
b = np.array([[10,20], [30,40]])
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print()

#행렬곱: matmul()
print(np.matmul(a,b))
print(a@b)  # == matmul
print(a[0,0]*b[0,0] + a[0,1]*b[1,0]) 
print(a[0,0]*b[0,1] + a[0,1]*b[1,1])
print(a[1,0]*b[0,0] + a[1,1]*b[1,0])
print(a[1,0]*b[0,1] + a[1,1]*b[1,1])

[[11 22]
 [33 44]]
[[ -9 -18]
 [-27 -36]]
[[ 10  40]
 [ 90 160]]
[[0.1 0.1]
 [0.1 0.1]]

[[ 70 100]
 [150 220]]
[[ 70 100]
 [150 220]]
70
100
150
220


In [49]:
#이차원 ndarray의 덧셈, 뺄셈, 곱셈, 나눗셈, 제곱
a = np.array([[1,2], [3,4]])
print(a+1)
print(a-1)
print(a*100)
print(a/100)
print(a**2)

[[2 3]
 [4 5]]
[[0 1]
 [2 3]]
[[100 200]
 [300 400]]
[[0.01 0.02]
 [0.03 0.04]]
[[ 1  4]
 [ 9 16]]


In [64]:
#LAB 11-3
#1
a = np.arange(1,10)
a = a.reshape(3,3)
print('a = ', a)
print()

b = np.ones((3,3))
b = b+1
print('b = ', b)
print()

print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a@b)
print(a**2)

a =  [[1 2 3]
 [4 5 6]
 [7 8 9]]

b =  [[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]

[[ 3.  4.  5.]
 [ 6.  7.  8.]
 [ 9. 10. 11.]]
[[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]]
[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]
[[0.5 1.  1.5]
 [2.  2.5 3. ]
 [3.5 4.  4.5]]
[[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [76]:
#ndarray의 생성

print(np.zeros((2,3))) #모든 값이 0인 2*3 크기 행렬
print(np.ones((2,3))) #모든 값이 1인 2*3 크기 행렬
print(np.full((2,3),100)) #모든 값이 100인 2*3 행렬
print(np.eye(3))  #3*3 크기의 단위행렬(단위행렬 : 정방행렬 중에서 대각선 성분이 1이고, 나머지 성분이 0인 행렬)
print(np.random.random((2,3))) #2*3 크기의 랜덤행렬
print(np.arange(0,10))
print(np.arange(0,10,2))
print(np.arange(0,10,3))
print(np.arange(0.0, 1.0, 0.2))
print(np.linspace(0,10,5))
print(np.linspace(0,10,4))

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[100 100 100]
 [100 100 100]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0.61007471 0.63014134 0.63081658]
 [0.45085846 0.886097   0.9127193 ]]
[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]
[0 3 6 9]
[0.  0.2 0.4 0.6 0.8]
[ 0.   2.5  5.   7.5 10. ]
[ 0.          3.33333333  6.66666667 10.        ]


In [82]:
#LAB 11-4

#1.
a1 = np.full((3,3),2)
print(a1)
print()

#2.
a2 = np.arange(1,13)
print(a2)
print()

#3.
a3 = np.arange(3,49,3)
print(a3)
print()

#4.
a4 = np.arange(0,21,5)
print(a4)

[[2 2 2]
 [2 2 2]
 [2 2 2]]

[ 1  2  3  4  5  6  7  8  9 10 11 12]

[ 3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48]

[ 0  5 10 15 20]


In [85]:
#ndarray의 재구성
temp = np.arange(0,10)
temp = temp.reshape(2,5)
print(temp)
print()

temp = np.arange(0,10)
temp = temp.reshape(5,2)
print(temp)

#temp = np.arange(0,10)
#temp.reshape(3,3)
#개수 안맞아서 오류

[[0 1 2 3 4]
 [5 6 7 8 9]]

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [92]:
temp = np.arange(0,24).reshape(4,3,2)
print(temp)
print()

a = np.arange(6).reshape(3,2)
print(a)
print()

a = np.transpose(a)  #행렬 차원을 뒤집음. (3,2)면 (2,3)으로
print(a)
print()

a = np.arange(15).reshape(3,5)
print(a, '\n')
a = np.transpose(a)
print(a)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]

[[0 1]
 [2 3]
 [4 5]]

[[0 2 4]
 [1 3 5]]

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]] 

[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [98]:
#LAB 11-5
#1
a1 = np.arange(1,13).reshape(2,6)
print('a1 = ', a1)
print()

#2
a2 = np.arange(1,31).reshape(3,10)
print('a2 = ', a2)
print()

#3
a3 = a2.reshape(6,5)
print('a3 = ', a3)
print()

#4
a4 = np.transpose(a3)
print('a4 = ', a4)

a1 =  [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]

a2 =  [[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]]

a3 =  [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]

a4 =  [[ 1  6 11 16 21 26]
 [ 2  7 12 17 22 27]
 [ 3  8 13 18 23 28]
 [ 4  9 14 19 24 29]
 [ 5 10 15 20 25 30]]


In [103]:
#참고: ndarray 출력할 때 콤마를 넣어서 출력하는 방법
ar = np.array([1,2,3,4,5])

#그냥 출력
print(ar)
#콤마 넣어서 출력
print(np.array2string(ar, separator = ','))
#repr() 함수 사용(represent)
print(repr(ar))

[1 2 3 4 5]
[1,2,3,4,5]
array([1, 2, 3, 4, 5])


In [106]:
#다차원 배열의 축
a = np.arange(0,6).reshape(3,2)
print(repr(a))

print(a.sum())
print(a.sum(axis = 0))  #0축 방향(열 방향) 원소의 합(위에서 아래로)
print(a.sum(axis = 1))  #1축 방향(행 방향) 원소의 합(왼쪽에서 오른쪽으로)

print()
print(a.min(axis = 0))
print(a.min(axis = 1))
print(a.max(axis = 0))
print(a.max(axis = 1))

array([[0, 1],
       [2, 3],
       [4, 5]])
15
[6 9]
[1 5 9]

[0 1]
[0 2 4]
[4 5]
[1 3 5]


In [107]:
a = np.array([1,3,4])
print(np.insert(a,1,2))
a = np.array([[1,1],[2,2],[3,3]])
print(np.insert(a,1,4, axis = 0))
print(np.insert(a,1,4, axis = 1))

[1 2 3 4]
[[1 1]
 [4 4]
 [2 2]
 [3 3]]
[[1 4 1]
 [2 4 2]
 [3 4 3]]


In [116]:
#LAB 11-6
#1
a = np.random.randint(1,100,15).reshape(3,5)
print('a = ', a)
print()

#2
print('a의 열방향 최댓값 : ', a.max(axis = 0))
print('a의 열방향 최솟값 : ', a.min(axis = 0))
print('a의 열방향 평균 : ', a.mean(axis = 0))
print()

#3
print('a의 행방향 최댓값 : ', a.max(axis = 1))
print('a의 행방향 최솟값 : ', a.min(axis = 1))
print('a의 행방향 평균 : ', a.mean(axis = 1))
print()

a =  [[29 77 85 91  8]
 [59 61 98 77 38]
 [43 99 57 94 52]]

a의 열방향 최댓값 :  [59 99 98 94 52]
a의 열방향 최솟값 :  [29 61 57 77  8]
a의 열방향 평균 :  [43.66666667 79.         80.         87.33333333 32.66666667]

a의 행방향 최댓값 :  [91 98 99]
a의 행방향 최솟값 :  [ 8 38 43]
a의 행방향 평균 :  [58.  66.6 69. ]



In [121]:
#배열의 인덱싱
a = np.array([1,2,3])
print(a[0], a[1], a[2])
print(a[-1], a[-2], a[-3])
print()

#여러 원소 인덱싱
a = np.array([1,2,3,4,5])
print(a[np.array([0,1])])
print(a[np.array([0,1,2])])
print(a[np.array([0,1,3])])
print(a[np.array([1,1,1,1])])
print()

#리스트와 슬라이싱
a_list = [10, 20, 30, 40, 50, 60, 70, 80]
print(a_list[1:5])
print()

#넘파이의 슬라이싱
a = np.array([10,20,30,40,50,60,70,80])
print(a[1:5])
print(a[1:])
print(a[:])
print(a[::2])  #양수 2의 스텝값
print(a[::-1]) #음수 스텝값

1 2 3
3 2 1

[1 2]
[1 2 3]
[1 2 4]
[2 2 2 2]

[20, 30, 40, 50]

[20 30 40 50]
[20 30 40 50 60 70 80]
[10 20 30 40 50 60 70 80]
[10 30 50 70]
[80 70 60 50 40 30 20 10]


In [126]:
#LAB 11-7
#1
a = np.arange(1,11)
print(a)
print(a[np.array([1,3,5,7])])

#2
b = a[5:]
c = a[6:]
d = a[:3]
e = a[::2]
f = a[::-2]
print(b)
print(c)
print(d)
print(e)
print(f)

[ 1  2  3  4  5  6  7  8  9 10]
[2 4 6 8]
[ 6  7  8  9 10]
[ 7  8  9 10]
[1 2 3]
[1 3 5 7 9]
[10  8  6  4  2]


In [168]:
#LAB 11-8
#1
a = np.arange(0,24).reshape(4,3,2)
print('index     element')
for i in range(4):
    for j in range(3):
        print('({},{},{})     '.format(i,j,0), a[i,j,0])
        print('({},{},{})     '.format(i,j,1), a[i,j,1])
print()
        
b = np.concatenate((a[0,0], a[1,0]), axis = 0)
print(repr(b))

c = np.concatenate((a[0,0], a[2,1]), axis = 0)
print(repr(c))

d = np.concatenate((a[0], a[1]), axis = 0)
print(repr(d))

e = np.concatenate((a[0], a[1]), axis = 1)
print(repr(e))

index     element
(0,0,0)      0
(0,0,1)      1
(0,1,0)      2
(0,1,1)      3
(0,2,0)      4
(0,2,1)      5
(1,0,0)      6
(1,0,1)      7
(1,1,0)      8
(1,1,1)      9
(1,2,0)      10
(1,2,1)      11
(2,0,0)      12
(2,0,1)      13
(2,1,0)      14
(2,1,1)      15
(2,2,0)      16
(2,2,1)      17
(3,0,0)      18
(3,0,1)      19
(3,1,0)      20
(3,1,1)      21
(3,2,0)      22
(3,2,1)      23

array([0, 1, 6, 7])
array([ 0,  1, 14, 15])
array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])
array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])


In [13]:
#LAB 11-9
#1
import numpy as np

a = np.arange(0,16).reshape(4,4)

b = a[:, 1]
print('b = ', b)

c = a[2, 1:]
print('c = ', c)

d = a[0:2, 0:2]
print('d = ', d)

e = a[1:3, 1:3]
print('e = ', e)


#2
f = a[:2, :3]
f = f.flatten()
print('f = ', f)

g = a[2:] #or g = a[2: , :]
g = g.flatten()
print('g = ', g)

temp_1 = a[1, 1:]
temp_2 = a[3, 1:]
h = np.append(temp_1, temp_2)
h = h.flatten()
print('h = ', h)

b =  [ 1  5  9 13]
c =  [ 9 10 11]
d =  [[0 1]
 [4 5]]
e =  [[ 5  6]
 [ 9 10]]
f =  [0 1 2 4 5 6]
g =  [ 8  9 10 11 12 13 14 15]
h =  [ 5  6  7 13 14 15]


In [127]:
#선형연립방정식
# 2x + 3y = 1
#  x - 2y = 4

a = np.array([[2,3], [1,-2]])  #계수
b = np.array([1,4])   #답
x = np.linalg.solve(a,b) 
print(x)

[ 2. -1.]


In [25]:
#LAB 11-10
#1
a = np.array([[1,1,-1], [2,-1,3], [1,2,1]])
b = np.array([[0], [9], [8]])
x = np.linalg.solve(a,b)
print('x = {:.1f}, y = {:.1f}, z = {:.1f}'.format(x[0,0], x[1,0], x[2,0]))
print()

#2
A = np.array([[1,1,-1], [2,-1,3], [1,2,1]], dtype = 'int32')
A = np.linalg.det(A)
print('{:.1f}'.format(A))
print()

#3
A = np.array([[1,1,-1], [2,-1,3], [1,2,1]], dtype = 'int32')
a = A[0,0]
b = A[0,1]
c = A[0,2]
a_mul = A[1:, 1:]
b_mul = A[1:, ::2]
c_mul = A[1:, :2]
a_mul = np.linalg.det(a_mul)
b_mul = np.linalg.det(b_mul)
c_mul = np.linalg.det(c_mul)
det_result = np.linalg.det(A)
mul_result = a*a_mul - b*b_mul + c*c_mul
print('3*3 행렬식 계산        :', det_result)
print('3개의 2*2 g행렬식 계산 :', mul_result)

x = 1.0, y = 2.0, z = 3.0

-11.0

3*3 행렬식 계산        : -11.000000000000002
3개의 2*2 g행렬식 계산 : -11.000000000000002
